---
ID: "878e7834-1e28-4105-b5e4-8f86b7ddafe1"
Parent: "156e5fee-d4ee-43c4-ba1c-2ccd8b027e9a"
Template: "156e5fee-d4ee-43c4-ba1c-2ccd8b027e9a"
Path: /sitecore/templates/Project/AMP/Content Types/Site Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180216T174643Z
